"""
core/config.py
──────────────
Central configuration for the entire API.
All file paths, CORS settings, and constants live here.
If anything changes (e.g. output folder moves), update HERE only.
"""

import os
from pathlib import Path

# ── Base Paths ────────────────────────────────────────────────────────────────
# This file is at: HealixPharm/backend/api/core/config.py
# We go up 3 levels to reach: HealixPharm/backend/
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# ML Pipeline root (where main.py lives)
ML_ROOT = BASE_DIR / "stock_management" / "Stock_prediction"

# ── Output File Paths (generated by main.py) ─────────────────────────────────
REPORTS_DIR   = ML_ROOT / "outputs" / "reports"
CHARTS_DIR    = ML_ROOT / "outputs" / "charts"

# CSV files that main.py generates
BUDGETS_CSV    = REPORTS_DIR / "frontend_category_budgets.csv"
INVENTORY_CSV  = REPORTS_DIR / "detailed_inventory_plan.csv"
EVALUATION_CSV = REPORTS_DIR / "model_evaluation.csv"
TRENDS_CSV     = ML_ROOT / "data" / "preprocessed_12_month_data.csv"
COMPARISON_CSV = REPORTS_DIR / "model_comparison.csv"

# Chart images
BUDGET_CHART_PNG = CHARTS_DIR / "category_budget_chart.png"
TRENDS_CHART_PNG = CHARTS_DIR / "monthly_category_trends.png"

# ── CORS Settings ─────────────────────────────────────────────────────────────
# These are the URLs allowed to call your API
# In development: React runs on localhost:3000
# In production:  replace with your actual domain
ALLOWED_ORIGINS = [
    "http://localhost:3000",      # React dev server
    "http://localhost:5173",      # Vite React dev server
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    # "https://yourdomain.com",   # Add production URL here later
]

# ── API Settings ──────────────────────────────────────────────────────────────
API_TITLE       = "HealixPharm Stock Prediction API"
API_DESCRIPTION = """
## Pharmacy Stock Prediction API

Provides ML-powered stock predictions for People's Pharmacy.

### Features
- 🔮 Predict monthly stock requirements using Random Forest ML
- 💰 Calculate budget requirements per category
- 📊 View 12-month sales trends
- 📈 Monitor model accuracy metrics
- 📦 Get detailed inventory plans
"""
API_VERSION     = "1.0.0"
API_PREFIX      = "/api/v1"   # All endpoints start with /api/v1/
