"""
services/ml_service.py
──────────────────────
The SERVICE layer — handles all business logic.

What this does:
1. Reads CSV files generated by main.py
2. Triggers the ML pipeline (main.py) when requested
3. Transforms raw CSV data into clean JSON-ready Python dicts
4. Handles all errors in one place

The ROUTER (predict.py) just calls these functions.
It never reads files or runs ML directly.
"""

import os
import sys
import time
import subprocess
import pandas as pd
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Any, Optional

# Add ML root to path so we can import from it
from core.config import (
    BASE_DIR,
    ML_ROOT,
    BUDGETS_CSV,
    INVENTORY_CSV,
    EVALUATION_CSV,
    TRENDS_CSV,
    COMPARISON_CSV,
)

# Month number → name lookup
MONTH_NAMES = {
    1: "January",  2: "February", 3: "March",
    4: "April",    5: "May",      6: "June",
    7: "July",     8: "August",   9: "September",
    10: "October", 11: "November",12: "December"
}


# ══════════════════════════════════════════════════════════════════════════════
# HELPER
# ══════════════════════════════════════════════════════════════════════════════

def _file_exists_or_raise(path: Path, hint: str = "") -> None:
    """
    Checks if a CSV file exists.
    If NOT → raises FileNotFoundError with a helpful message.
    This prevents cryptic pandas errors reaching the frontend.
    """
    if not path.exists():
        msg = f"File not found: {path.name}."
        if hint:
            msg += f" {hint}"
        raise FileNotFoundError(msg)


def _get_target_month_from_csv(csv_path: Path) -> str:
    """
    Reads the predicted quantity column name from the CSV
    to extract the target month (e.g. 'April 2026').
    Column looks like: 'Predicted_April_2026_Qty'
    """
    try:
        df = pd.read_csv(csv_path, nrows=0)  # read headers only
        pred_cols = [c for c in df.columns if c.startswith("Predicted_")]
        if pred_cols:
            # 'Predicted_April_2026_Qty' → 'April 2026'
            parts = pred_cols[0].replace("Predicted_", "").replace("_Qty", "")
            return parts.replace("_", " ")
    except Exception:
        pass
    return "Next Month"


# ══════════════════════════════════════════════════════════════════════════════
# SERVICE FUNCTIONS
# ══════════════════════════════════════════════════════════════════════════════

def run_ml_pipeline() -> Dict[str, Any]:
    """
    Triggers main.py as a subprocess.

    Why subprocess?
    main.py takes 40-60 seconds to run.
    Running it as subprocess means the API stays responsive
    and we can capture its output/errors cleanly.

    Returns dict with status, budget, timing info.
    """
    start_time = time.time()

    main_py_path = ML_ROOT / "main.py"

    if not main_py_path.exists():
        raise FileNotFoundError(
            f"main.py not found at {main_py_path}. "
            "Check ML_ROOT in config.py"
        )

    # Find the root unified venv python (to ensure all ML libraries are present)
    root_venv_python = BASE_DIR.parent / "venv" / "Scripts" / "python.exe"
    
    # Fallback to current interpreter if root venv isn't found
    python_exe = str(root_venv_python) if root_venv_python.exists() else sys.executable

    # Run main.py using the robust python interpreter
    result = subprocess.run(
        [python_exe, str(main_py_path)],
        cwd=str(ML_ROOT),          # run FROM the ML folder
        capture_output=True,       # capture stdout and stderr
        text=True,                 # return strings not bytes
        encoding="utf-8",          # handle emojis/special chars on Windows
        env={**os.environ, "PYTHONIOENCODING": "utf-8"},
        timeout=300,               # 5 min max (safety limit)
    )

    elapsed = round(time.time() - start_time, 2)

    # If main.py crashed → return error details
    if result.returncode != 0:
        raise RuntimeError(
            f"ML pipeline failed after {elapsed}s.\n"
            f"Error output:\n{result.stderr}"
        )

    # Extract total budget from main.py's printed output
    total_budget = 0.0
    items_predicted = 0
    target_month = "Next Month"

    for line in result.stdout.split("\n"):
        # Updated string match to "Total budget" to align with main.py output
        if "Total budget" in line:
            # Line: "   [+] Total budget: Rs. 40,935,807.31"
            try:
                budget_str = line.split("Rs.")[-1].strip().replace(",", "")
                total_budget = float(budget_str)
            except ValueError:
                pass
        if "Items predicted" in line:
            # Line: "   Items predicted: 5024"
            try:
                items_predicted = int(line.split(":")[-1].strip())
            except ValueError:
                pass
        if "Target month" in line:
            # Line: "   Target month   : April 2026"
            try:
                target_month = line.split(":")[-1].strip()
            except Exception:
                pass

    return {
        "status": "success",
        "message": "Prediction pipeline completed successfully",
        "target_month": target_month,
        "items_predicted": items_predicted,
        "total_budget": total_budget,
        "time_taken_seconds": elapsed,
        "timestamp": datetime.now().isoformat(),
    }


# ─────────────────────────────────────────────────────────────────────────────

def get_budgets() -> Dict[str, Any]:
    """
    Reads frontend_category_budgets.csv
    Returns category budgets sorted highest first.

    CSV columns: Category, Budget_Required
    """
    _file_exists_or_raise(
        BUDGETS_CSV,
        hint="Run POST /api/v1/predict/run first to generate predictions."
    )

    df = pd.read_csv(BUDGETS_CSV)
    df = df.sort_values("Budget_Required", ascending=False)

    # Get target month from inventory CSV (more reliable)
    target_month = "Next Month"
    if INVENTORY_CSV.exists():
        target_month = _get_target_month_from_csv(INVENTORY_CSV)

    categories = [
        {
            "category": row["Category"],
            "budget_required": round(float(row["Budget_Required"]), 2),
        }
        for _, row in df.iterrows()
    ]

    return {
        "target_month": target_month,
        "total_budget": round(df["Budget_Required"].sum(), 2),
        "categories": categories,
        "count": len(categories),
    }


# ─────────────────────────────────────────────────────────────────────────────

def get_inventory(
    category: Optional[str] = None,
    search: Optional[str] = None,
    limit: int = 100,
    offset: int = 0,
) -> Dict[str, Any]:
    """
    Reads detailed_inventory_plan.csv
    Supports filtering by category and search by item name.
    Supports pagination (limit/offset).

    CSV columns: Item, Category, Predicted_*_Qty,
                 Recommended_Stock, Price, Budget_Required
    """
    _file_exists_or_raise(
        INVENTORY_CSV,
        hint="Run POST /api/v1/predict/run first."
    )

    df = pd.read_csv(INVENTORY_CSV)

    # Find the predicted qty column (name changes each month)
    pred_col = next(
        (c for c in df.columns if c.startswith("Predicted_")), None
    )
    target_month = "Next Month"
    if pred_col:
        target_month = pred_col.replace("Predicted_", "").replace("_Qty", "").replace("_", " ")

    # Apply category filter
    if category:
        df = df[df["Category"].str.lower() == category.lower()]

    # Apply search filter (item name contains search string)
    if search:
        df = df[df["Item"].str.upper().str.contains(search.upper(), na=False)]

    total_items = len(df)

    # Apply pagination
    df_page = df.iloc[offset: offset + limit]

    items = []
    for _, row in df_page.iterrows():
        predicted_qty = int(row[pred_col]) if pred_col else 0
        items.append({
            "item": str(row["Item"]),
            "category": str(row["Category"]),
            "predicted_qty": predicted_qty,
            "recommended_stock": int(row.get("Recommended_Stock", 0)),
            "price": round(float(row.get("Price", 0)), 2),
            "budget_required": round(float(row.get("Budget_Required", 0)), 2),
        })

    return {
        "target_month": target_month,
        "total_items": total_items,
        "limit": limit,
        "offset": offset,
        "items": items,
    }


# ─────────────────────────────────────────────────────────────────────────────

def get_evaluation() -> Dict[str, Any]:
    """
    Reads model_evaluation.csv
    Returns ML accuracy metrics.

    CSV columns: Metric, Value, Interpretation
    """
    _file_exists_or_raise(
        EVALUATION_CSV,
        hint="Run POST /api/v1/predict/run first."
    )

    df = pd.read_csv(EVALUATION_CSV)

    # Convert rows to a simple key→value dict
    metrics = {
        str(row["Metric"]): row["Value"]
        for _, row in df.iterrows()
    }

    r2 = float(metrics.get("R2_Score", 0))

    if r2 >= 0.85:
        verdict = "Excellent"
        interpretation = f"Model explains {r2*100:.1f}% of sales variation. Highly reliable."
    elif r2 >= 0.70:
        verdict = "Good"
        interpretation = f"Model explains {r2*100:.1f}% of sales variation. Reliable for ordering."
    elif r2 >= 0.50:
        verdict = "Acceptable"
        interpretation = f"Model explains {r2*100:.1f}% of sales variation. Use with 20% safety buffer."
    else:
        verdict = "Needs Improvement"
        interpretation = f"Model explains {r2*100:.1f}% of sales variation. More data needed."

    return {
        "mae": round(float(metrics.get("MAE", 0)), 4),
        "rmse": round(float(metrics.get("RMSE", 0)), 4),
        "r2_score": round(r2, 4),
        "mape": round(float(metrics.get("MAPE (%)", 0)), 4),
        "verdict": verdict,
        "interpretation": interpretation,
    }


# ─────────────────────────────────────────────────────────────────────────────

def get_trends() -> Dict[str, Any]:
    """
    Reads preprocessed_12_month_data.csv
    Returns monthly sales totals per category for line charts.

    Excludes 'Other Meds/Unclassified' (too noisy for trends).
    """
    _file_exists_or_raise(
        TRENDS_CSV,
        hint="Run POST /api/v1/predict/run first."
    )

    df = pd.read_csv(TRENDS_CSV)

    # Aggregate: total qty per month per category
    trend_df = (
        df.groupby(["Month", "Category"])["Qty"]
        .sum()
        .reset_index()
    )

    # Remove noisy unclassified category
    trend_df = trend_df[trend_df["Category"] != "Other Meds/Unclassified"]

    # Sort by month
    trend_df = trend_df.sort_values(["Category", "Month"])

    # Build date range string
    date_range = "Apr 2025 - Mar 2026"
    if "Date" in df.columns:
        try:
            dates = pd.to_datetime(df["Date"], errors="coerce")
            min_d = dates.min().strftime("%b %Y")
            max_d = dates.max().strftime("%b %Y")
            date_range = f"{min_d} - {max_d}"
        except Exception:
            pass

    categories = sorted(trend_df["Category"].unique().tolist())

    data_points = [
        {
            "month": int(row["Month"]),
            "month_name": MONTH_NAMES.get(int(row["Month"]), str(row["Month"])),
            "category": str(row["Category"]),
            "total_qty": round(float(row["Qty"]), 2),
        }
        for _, row in trend_df.iterrows()
    ]

    return {
        "date_range": date_range,
        "categories": categories,
        "data": data_points,
    }


# ─────────────────────────────────────────────────────────────────────────────

def get_summary() -> Dict[str, Any]:
    """
    Aggregates key numbers for the main dashboard summary card.
    Combines data from budgets + evaluation + trends CSVs.
    """
    summary = {
        "target_month": "Not yet run",
        "total_budget": 0.0,
        "total_items": 0,
        "top_category": "N/A",
        "top_category_budget": 0.0,
        "model_r2": 0.0,
        "model_verdict": "Not yet evaluated",
        "last_run": None,
        "data_date_range": "N/A",
    }

    # Budget info
    if BUDGETS_CSV.exists():
        budgets = get_budgets()
        summary["target_month"] = budgets["target_month"]
        summary["total_budget"] = budgets["total_budget"]
        if budgets["categories"]:
            top = budgets["categories"][0]
            summary["top_category"] = top["category"]
            summary["top_category_budget"] = top["budget_required"]
        # Last modified time of budgets CSV = last run time
        mtime = os.path.getmtime(BUDGETS_CSV)
        summary["last_run"] = datetime.fromtimestamp(mtime).isoformat()

    # Item count
    if INVENTORY_CSV.exists():
        inv_df = pd.read_csv(INVENTORY_CSV)
        summary["total_items"] = len(inv_df)

    # Model accuracy
    if EVALUATION_CSV.exists():
        evaluation = get_evaluation()
        summary["model_r2"] = evaluation["r2_score"]
        summary["model_verdict"] = evaluation["verdict"]

    # Date range
    if TRENDS_CSV.exists():
        try:
            df = pd.read_csv(TRENDS_CSV, usecols=["Date"])
            dates = pd.to_datetime(df["Date"], errors="coerce")
            summary["data_date_range"] = (
                f"{dates.min().strftime('%b %Y')} - "
                f"{dates.max().strftime('%b %Y')}"
            )
        except Exception:
            pass

    return summary
