"""
core/config.py
──────────────
Central configuration — all paths and settings in one place.
Every other file imports from here.
If any path changes → update THIS file only.
"""

from pathlib import Path

# ── Where is this file? ───────────────────────────────────────────────────────
# This file lives at:   backend/api/core/config.py
# .parent               = backend/api/core/
# .parent.parent        = backend/api/
# .parent.parent.parent = backend/
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# ── Where is the ML pipeline? ─────────────────────────────────────────────────
ML_ROOT = BASE_DIR / "stock_management" / "Stock_prediction"

# ── Where are the output folders? ─────────────────────────────────────────────
REPORTS_DIR = ML_ROOT / "outputs" / "reports"
CHARTS_DIR  = ML_ROOT / "outputs" / "charts"

# ── CSV files generated by ML main.py ─────────────────────────────────────────
BUDGETS_CSV    = REPORTS_DIR / "frontend_category_budgets.csv"
INVENTORY_CSV  = REPORTS_DIR / "detailed_inventory_plan.csv"
EVALUATION_CSV = REPORTS_DIR / "model_evaluation.csv"
COMPARISON_CSV = REPORTS_DIR / "model_comparison.csv"
TRENDS_CSV     = ML_ROOT / "data" / "preprocessed_12_month_data.csv"

# ── Chart images generated by ML main.py ──────────────────────────────────────
BUDGET_CHART_PNG = CHARTS_DIR / "category_budget_chart.png"
TRENDS_CHART_PNG = CHARTS_DIR / "monthly_category_trends.png"

# ── CORS settings ─────────────────────────────────────────────────────────────
ALLOWED_ORIGINS = [
   "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:3002",   
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "http://127.0.0.1:3002",
    "http://127.0.0.1:5173",
    "http://10.229.45.189:3000",
    "http://10.229.45.189:3001",
]

# ── API metadata ──────────────────────────────────────────────────────────────
API_TITLE = "HealixPharm Stock Prediction API"

API_DESCRIPTION = """
## HealixPharm Stock Prediction API

ML-powered stock predictions for People's Pharmacy.

### How To Use
1. Call **POST /api/v1/predict/run** first to generate predictions
2. Then call any GET endpoint to retrieve the results

### Available Endpoints
- **POST /predict/run** — Run the ML prediction pipeline (~60 seconds)
- **GET  /predict/summary** — Dashboard overview card
- **GET  /predict/budgets** — Budget per medicine category
- **GET  /predict/inventory** — Full item inventory plan
- **GET  /predict/evaluation** — Model accuracy metrics
- **GET  /predict/trends** — 12-month sales trends
"""

API_VERSION = "1.0.0"
API_PREFIX  = "/api/v1"
