from pathlib import Path

# ── WHERE IS THIS FILE? ───────────────────────────────
# config.py lives at:
# backend/api/core/config.py
#
# .parent      = backend/api/core/
# .parent.parent     = backend/api/
# .parent.parent.parent  = backend/
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# ── WHERE IS THE ML PIPELINE? ─────────────────────────
# backend/ + stock_management/Stock_prediction/
ML_ROOT = BASE_DIR / "stock_management" / "Stock_prediction"

# ── WHERE ARE THE CSV FILES? ──────────────────────────
# These are generated by your ML main.py
BUDGETS_CSV = ML_ROOT / "outputs" / "reports" / "frontend_category_budgets.csv"
INVENTORY_CSV = ML_ROOT / "outputs" / "reports" / "detailed_inventory_plan.csv"
EVALUATION_CSV = ML_ROOT / "outputs" / "reports" / "model_evaluation.csv"
TRENDS_CSV = ML_ROOT / "data" / "preprocessed_12_month_data.csv"

# ── WHO IS ALLOWED TO CALL THIS API? ──────────────────
# React runs on port 3000 or 5173
# Without this → browser BLOCKS React from calling API
ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React (Create React App)
    "http://localhost:5173",  # React (Vite)
]

# ── API INFORMATION ───────────────────────────────────
API_TITLE = "HealixPharm Stock Prediction API"
API_VERSION = "1.0.0"
API_PREFIX = "/api/v1"  # all URLs start with this
